#!/bin/bash

NW_DIR="b"
NW_URI=https://github.com/nwjs
NW_VER=74

UP_DIR="a"

CHROMIUM_URI="https://github.com/chromium/chromium"
CHROMIUM_VER="111.0.5563.65"

NODE_URI="https://github.com/nodejs/node"
NODE_VER="19.7.0"

V8_URI="https://github.com/v8/v8"
V8_VER="11.1.277.13"

if [[ ! -d "diff" ]]; then
    mkdir diff
fi

if [[ -d "diff/0.$NW_VER.x" ]]; then
    echo "Patches already exist. Exiting..."
    exit 0
fi

cd diff

if [[ ! -d $NW_DIR ]]; then
    mkdir $NW_DIR
fi

if [[ ! -d "$NW_DIR/chromium" ]]; then
    git clone --branch=nw$NW_VER --depth=1 $NW_URI/chromium.src.git $NW_DIR/chromium
fi

if [[ ! -d "$NW_DIR/node" ]]; then
    git clone --branch=nw$NW_VER --depth=1 $NW_URI/node.git $NW_DIR/node
fi

if [[ ! -d "$NW_DIR/v8" ]]; then
    git clone --branch=nw$NW_VER --depth=1 $NW_URI/v8.git $NW_DIR/v8
fi

if [[ ! -d $UP_DIR ]]; then
    mkdir $UP_DIR
fi

if [[ ! -d "$UP_DIR/chromium" ]]; then
    curl -L $CHROMIUM_URI/archive/refs/tags/$CHROMIUM_VER.tar.gz | tar -xz -C $UP_DIR
    mv $UP_DIR/chromium-$CHROMIUM_VER $UP_DIR/chromium
fi

if [[ ! -d "$UP_DIR/node" ]]; then
    curl -L $NODE_URI/archive/refs/tags/v$NODE_VER.tar.gz | tar -xz -C $UP_DIR
    mv $UP_DIR/node-$NODE_VER $UP_DIR/node
fi

if [[ ! -d "$UP_DIR/v8" ]]; then
    curl -L $V8_URI/archive/refs/tags/$V8_VER.tar.gz | tar -xz -C $UP_DIR
    mv $UP_DIR/v8-$V8_VER $UP_DIR/v8
fi

if [[ ! -d "0.$NW_VER.x" ]]; then
    mkdir 0.$NW_VER.x
fi

diff -r -u --color $UP_DIR/chromium $NW_DIR/chromium > 0.$NW_VER.x/chromium.patch

diff -r -u --color $UP_DIR/node $NW_DIR/node > 0.$NW_VER.x/node.patch

diff -r -u --color $UP_DIR/v8 $NW_DIR/v8 > 0.$NW_VER.x/v8.patch

rm -rf $NW_DIR $UP_DIR
