#!/bin/bash

NW_VER=14

if [[ ! -d "patches" ]]; then
    mkdir patches
fi

if [[ ! -d "patches/chromium" ]]; then
    mkdir patches/chromium
fi

if [[ ! -d "patches/node" ]]; then
    mkdir patches/node
fi

if [[ ! -d "patches/v8" ]]; then
    mkdir patches/v8
fi

splitdiff -a -p 2 -d -D ./patches/0.$NW_VER.x/chromium ./diff/0.$NW_VER.x/chromium.patch

splitdiff -a -p 2 -d -D ./patches/0.$NW_VER.x/node ./diff/0.$NW_VER.x/node.patch

splitdiff -a -p 2 -d -D ./patches/0.$NW_VER.x/v8 ./diff/0.$NW_VER.x/v8.patch
