build:
	chmod 755 ./scripts/build
	bash ./scripts/build

clean:
	rm -rf src _bad_scm .gclient

patch:
	chmod 755 ./scripts/patch
	bash ./scripts/patch

split:
	chmod 755 ./scripts/split
	bash ./scripts/split
