#!/bin/bash

DEPOT_TOOLS_DIR="depot_tools"
DEPOT_TOOLS_URI="https://chromium.googlesource.com/chromium/tools/depot_tools.git"

CHROMIUM_DIR="chromium"
CHROMIUM_URI="https://github.com/tharatau/nw-chromium"

NODE_DIR="third_party/node-nw"
NODE_URI="https://github.com/nwjs/node"

NW_DIR="content/nw"
NW_URI="https://github.com/nwjs/nw.js"

V8_DIR="v8"
V8_URI="https://github.com/nwjs/v8"

if [[ ! -d $DEPOT_TOOLS_DIR ]]; then
    git clone $DEPOT_TOOLS_URI $DEPOT_TOOLS_DIR
fi

export PATH="$PATH:${PWD}/depot_tools"

if [[ ! -d $CHROMIUM_DIR ]]; then
    mkdir $CHROMIUM_DIR
fi

cd $CHROMIUM_DIR

if [[ ! -f ".gclient" ]]; then
    gclient config --name=src $CHROMIUM_URI
    gclient sync --no-history
fi

cd src

# ./build/install-build-deps.sh

if [[ ! -d $NW_DIR ]]; then
    git clone -b nw72 --depth=1 $NW_URI $NW_DIR
fi

if [[ ! -d $NODE_DIR ]]; then
    git clone -b nw72 --depth=1 $NODE_URI $NODE_DIR
fi

if [[ ! -d $V8_DIR ]]; then
    git clone -b nw72 --depth=1 $V8_URI $v8_DIR
fi

cat <<CONFIG > "./build/util/LASTCHANGE"
LASTCHANGE=0000000000000000000000000000000000000000-0000000000000000000000000000000000000000
LASTCHANGE_YEAR=1970
CONFIG

gclient sync --verbose