#!/bin/bash

NW_DIR="nw"
NW_URI=https://github.com/nwjs
NW_VER=72

UP_DIR="up"

CHROMIUM_URI="https://github.com/chromium/chromium"
CHROMIUM_VER="109.0.5414.87"

NODE_URI="https://github.com/nodejs/node"
NODE_VER="19.3.0"

V8_URI="https://github.com/v8/v8"
V8_VER="10.8.168.21"

if [[ ! -d "patches" ]]; then
    mkdir patches
fi

cd patches

if [[ ! -d $NW_DIR ]]; then
    mkdir $NW_DIR
fi

if [[ ! -d "$NW_DIR/chromium" ]]; then
    git clone --branch=nw$NW_VER --depth=1 $NW_URI/chromium.src.git $NW_DIR/chromium
fi

if [[ ! -d "$NW_DIR/node" ]]; then
    git clone --branch=nw$NW_VER --depth=1 $NW_URI/node.git $NW_DIR/node
fi

if [[ ! -d "$NW_DIR/v8" ]]; then
    git clone --branch=nw$NW_VER --depth=1 $NW_URI/v8.git $NW_DIR/v8
fi

if [[ ! -d $UP_DIR ]]; then
    mkdir $UP_DIR
fi

if [[ ! -d "$UP_DIR/chromium" ]]; then
    curl -L $CHROMIUM_URI/archive/refs/tags/$CHROMIUM_VER.tar.gz | tar -xz -C $UP_DIR
    mv $UP_DIR/chromium-$CHROMIUM_VER $UP_DIR/chromium
fi

if [[ ! -d "$UP_DIR/node" ]]; then
    curl -L $NODE_URI/archive/refs/tags/$NODE_VER.tar.gz | tar -xz -C $UP_DIR
    mv $UP_DIR/node-$NODE_VER $UP_DIR/node
fi

if [[ ! -d "$UP_DIR/v8" ]]; then
    curl -L $V8_URI/archive/refs/tags/$V8_VER.tar.gz | tar -xz -C $UP_DIR
    mv $UP_DIR/v8-$V8_VER $UP_DIR/v8
fi

if [[ ! -d "0.$NW_VER.x" ]]; then
    mkdir 0.$NW_VER.x
fi

diff -r -u --color up/v8 nw/v8 > 0.$NW_VER.x/v8.patch