name: patch
  on:
    pull_request:
      branches:
      - main

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: GuillaumeFalourd/git-commit-push@v1.3