name: nw
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: lib/nw

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  patch:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "19.7"
      - name: Install dependencies
        run: npm run patch:deps

      - name: Make patches
        if: steps.cache-patches.outputs.cache-hit != 'true'
        run: npm run patch:diff

      - name: Split patches
        run: npm run patch:split

      - name: Cache patches
        id: cache-patches
        uses: actions/cache@v3.3.1
        with:
          path: nw-toolkit/patches
          key: ${{ runner.os }}-patches

      - name: Commit patches
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          access_token: ${{ github.token }}
          commit_message: "ci: update patches"
          files: diff/ patches/
          force: true
