name: nw
on:
  push:
    branches:
      - main
    paths:
      - lib/nw/scripts/patch

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: lib/nw

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "19.5.0"
      - name: Make patches
        if: steps.cache-patches.outputs.cache-hit != 'true'
        run: npm run patch

      - name: Cache patches
        id: cache-patches
        uses: actions/cache@v3
        with:
          path: nw-toolkit/patches
          key: ${{ runner.os }}-patches

      - name: Commit patches
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          commit_message: "nw: update patches"
          files: lib/nw
